php:
  preset: laravel
<<<<<<< HEAD
=======
  version: 8
>>>>>>> edeeaa1b89af8af2dc16a2bda625163283dedbd2
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.php
<<<<<<< HEAD
js:
  finder:
    not-name:
      - vite.config.js
=======
      - server.php
js:
  finder:
    not-name:
      - webpack.mix.js
>>>>>>> edeeaa1b89af8af2dc16a2bda625163283dedbd2
css: true
